twig:
  file_name_pattern: '*.twig'
  form_themes:
    - bootstrap_5_layout.html.twig

  globals:
    reglage_id: '%reglage_id%'
    WS: Web symphonie
    WSLINK: https://web-symphonie.com
    reglages: '@App\SharedKernel\Domain\Service\Context\ContextInterface'
    permission: '@App\IdentityAndAccess\Domain\Service\User\UserPermissionsService'

when@test:
  twig:
    strict_variables: true
